# Generated by Django 4.0.4 on 2022-06-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'managed': False, 'ordering': ['name', 'country']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'managed': False, 'ordering': ['date', 'stage', 'country', 'league']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False, 'ordering': ['name', 'birthday', '-height', '-weight']},
        ),
        migrations.AlterModelOptions(
            name='playerattr',
            options={'managed': False, 'ordering': ['player', 'date', '-overall_rating']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teamattr',
            options={'managed': False, 'ordering': ['team', 'date']},
        ),
    ]
